module.exports.ERROR_VALIDATION = 400;
module.exports.ERROR_NOT_FOUND = 404;
module.exports.ERROR_UNAUTHORIZED = 401;
module.exports.ERROR_FORBIDDEN = 403;
module.exports.ERROR_CONFLICT = 409;
module.exports.ERROR_SERVER = 500;
module.exports.CODE_DUPLICATE = 11000;
module.exports.JWT_KEY = 's1R6p5JdXypUkOcBIh0bacWanLILTx2L';
module.exports.URL_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9-._~:/?#[\]@!$&'()*+,;=]{1,256}/;
